use_frameworks!
inhibit_all_warnings!

def standard_pods
  platform :ios, '14.5'
  pod 'EtherKit', :path => '../'
end

target 'EtherKit_Example' do
  standard_pods
end

target 'EtherKit_Tests' do
  standard_pods
  pod 'SwiftCheck'
end

